Delete empty file TaskContinuityMessageTest.java
This fixes an error when running atest:

atest.test_finders.test_filter_utils.MissingPackageNameError: [...]/frameworks/base/services/tests/servicestests/src/com/android/server/companion/datatransfer/continuity/messages/TaskContinuityMessageTest.java: Test class java file does not contain a package name.

Bug: 400970610
Flag: TEST_ONLY
Test: atest no longer fails
Change-Id: I329ea245f370433640aab270b710e7608dd2111f