Revert "[TouchLatency] Update style of touch latency"
This reverts commit 56f72145c7879bd1c8ae9a29470153c7051aa44f.

Reason for revert: Build error with Android Studio:
ERROR: /frameworks/base/tests/TouchLatency/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml:1630: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

Change-Id: I16091f405475a57156a4d62b7dad0853530ab81d