Remove flag wait_for_internet_ror
Since this flag was launched, remove it and make the corresponding code
unconditional.

Note that locksettings_flags_lib has to be removed rather than left
empty, since otherwise the following build error occurs:

    Error: failed to create java lib

    Caused by:
        production library contains no production flags

Bug: 231660348
Test: atest FrameworksServicesTests:com.android.server.locksettings
Flag: EXEMPT removing wait_for_internet_ror
Change-Id: Ic09ef94b3c3f499cdd987fee04a2742127e9c88a