Revert "Use Flag instead of method check to detect new message queue testability API"
This reverts commit 68e3f4387939af51eb7c8c592fa34e3820b48037.

Reason for revert: somehow incompatible with mainline R/S/T/U/V

https://android-build.corp.google.com/test_investigate/?blocking=blocking&status=none&invocationId=I90800010367953228&testResultId=TR09129634304861714&legacy=

java.lang.NoClassDefFoundError: android.net.connectivity.android.os.test.TestLooper
	at android.net.connectivity.com.android.server.connectivity.MulticastRoutingCoordinatorServiceTest.prepareService(MulticastRoutingCoordinatorServiceTest.kt:153)
	at android.net.connectivity.com.android.server.connectivity.MulticastRoutingCoordinatorServiceTest.testConstructor_multicastRoutingSocketIsCreated(MulticastRoutingCoordinatorServiceTest.kt:204)
	... 8 trimmed
Caused by: java.lang.NoSuchMethodError: No static method messageQueueTestability()Z in class Lcom/android/internal/hidden_from_bootclasspath/android/os/Flags; or its super classes (declaration of 'com.android.internal.hidden_from_bootclasspath.android.os.Flags' appears in /system/framework/framework.jar!classes4.dex)
	at android.net.connectivity.android.os.test.TestLooper.newTestabilityApisSupported(TestLooper.java:71)
	at android.net.connectivity.android.os.test.TestLooper.<clinit>(TestLooper.java:84)
	at android.net.connectivity.com.android.server.connectivity.MulticastRoutingCoordinatorServiceTest.prepareService(MulticastRoutingCoordinatorServiceTest.kt:153)
	at android.net.connectivity.com.android.server.connectivity.MulticastRoutingCoordinatorServiceTest.testMulticastRouting_applyForwardNone(MulticastRoutingCoordinatorServiceTest.kt:210)
	... 9 more

Change-Id: I40192ddd4366792b6d8742826e575b2569337c85