[Catalyst] Adds sdk_version: "system_current"
Make Catalyst libraries not depend on private platform APIs, and
get rid of weird NoClassDefFoundError in permission controller tests.

Bug: 420889528
Flag: EXEMPT build file
Test: presubmit&ABTD
Change-Id: Ibfc0520dcd1c2d49db492ea891984093d7719356